adds proper test file :seedling:

diff --git a/xml_parsing/p2_test b/xml_parsing/p2_test
--- a/xml_parsing/p2_test
+++ b/xml_parsing/p2_test
@@ -1,25 +1,78 @@
 #!/bin/bash
+GRADING_DIR=$HOME/grading
+TMP_DIR=/tmp/p2-grading/
+REQUIRED_FILES="create.sql drop.sql load.sql queries.sql runLoad.sh build.xml README.txt"
 
-# Run the drop.sql batch file to drop existing tables
-# Inside the drop.sql, you sould check whether the table exists. Drop them ONLY if they exists.
-mysql CS144 < drop.sql
+# usage
+if [ $# -ne 1 ]
+then
+     echo "Usage: $0 project2.zip" 1>&2
+     exit
+fi
 
-# Run the create.sql batch file to create the database and tables
-mysql CS144 < create.sql
+# make sure that the script runs on VM
+if [ `hostname` != "class-vm" ]; then
+     echo "ERROR: You need to run this script within the class virtual machine" 1>&2
+     exit
+fi
 
-# Compile and run the parser to generate the appropriate load files
-ant
-ant run-all
-...
+ZIP_FILE=$1
 
-# If the Java code does not handle duplicate removal, do this now
-sort ...
-...
+# clean any existing files
+rm -rf ${TMP_DIR}
 
-# Run the load.sql batch file to load the data
-mysql CS144 < load.sql
+# create temporary directory used for grading
+mkdir ${TMP_DIR}
 
-# Remove all temporary files
-rm ...
-...
+# unzip the submission zip file 
+if [ ! -f ${ZIP_FILE} ]; then
+    echo "ERROR: Cannot find $ZIP_FILE" 1>&2
+    rm -rf ${TMP_DIR}
+    exit 1
+fi
+unzip -q -d ${TMP_DIR} ${ZIP_FILE}
+if [ "$?" -ne "0" ]; then 
+    echo "ERROR: Cannot unzip ${ZIP_FILE} to ${TMP_DIR}"
+    rm -rf ${TMP_DIR}
+    exit 1
+fi
 
+# change directory to the grading folder
+cd ${TMP_DIR}
+
+# check the existence of the required files
+for FILE in ${REQUIRED_FILES}
+do
+    if [ ! -f ${FILE} ]; then
+	echo "ERROR: Cannot find ${FILE} in the root folder of your zip file" 1>&2
+	rm -rf ${TMP_DIR}
+	exit 1
+    fi
+done
+JAVA_FILES=`find src -name '*.java' -print`
+if [ -z "${JAVA_FILES}" ]; then
+    echo "ERROR: No java file is included in src folder of your zip file" 1>&2
+    rm -rf ${TMP_DIR}
+    exit 1
+fi
+
+# drop and re-create CS144 database to make sure a clean start
+echo "DROP DATABASE IF EXISTS CS144; CREATE DATABASE CS144;" | mysql -uroot -ppassword
+
+# parse the XML data and run the load script
+echo "Running your runLoad.sh script..."
+./runLoad.sh
+
+# run the queries
+echo "Running your query.sql script..."
+mysql CS144 < queries.sql
+
+# echo reminder message
+echo
+echo
+echo "Finished running your queries."
+echo "Please make sure that you got correct results from your queries"
+
+# clean up
+rm -rf ${TMP_DIR}
+exit 0
